config/routes.rb
PageMe::Application.routes.draw do
  resources :groups

  resources :children

end

app/models/child.rb
class Child < ActiveRecord::Base
	belongs_to :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    @children = Child.all
  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)
    if @child.save
      flash.notice = "Text Sent"
      redirect_to @child
      # Instantiate a Twilio client
      client = Twilio::REST::Client.new(TWILIO_CONFIG['sid'], TWILIO_CONFIG['token'])
      
      # Create and send an SMS message
      client.account.sms.messages.create(
        from: TWILIO_CONFIG['from'],
        to: @child.phone_number,
        body: "Please come pick up your child, #{@child.name}, Reason: #{@child.description} "
      )
    else
      render :new
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:name, :family, :phone_number, :email_address, :description)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name, :group_room)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/children/_form.html.erb
<%= semantic_form_for(@child) do |form| %>
<%= form.inputs do%>

<%= form.input :name %>
<%= form.input :phone_number %>
<%= form.input :email_address %>
<%= form.input :description%>
<%= form.collection_select :group_id, Group.all, :id, :group_name, :null => :false, :prompt => "Please select childs group" %> 
<% end %> 
<br> 
<br>
<%= form.buttons %>
 
 <% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<h1>Active</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Family</th>
      <th>Phone number</th>
      <th>Email address</th>
      <th>Last Updated</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.family %></td>
        <td><%= child.phone_number %></td>
        <td><%= child.email_address %></td>
        <td><%= child.updated_at.to_s(:short)%></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Update', edit_child_path(child) %></td>
        <td><%= link_to 'Delete', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_groups_path %>

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @child.name %>
</p>

<p>
  <strong>Family:</strong>
  <%= @child.family %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @child.phone_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @child.email_address %>
</p>
<p>
  <strong>Reason:</strong>
  <%= @child.description %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br>
    <%= f.text_field :group_name %>
  </div>
  <div class="field">
    <%= f.label :group_room %><br>
    <%= f.text_field :group_room %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Group name</th>
      <th>Group room</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= group.group_room %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @group.group_name %>
</p>

<p>
  <strong>Group room:</strong>
  <%= @group.group_room %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PageMe</title>
  <%= stylesheet_link_tag    "application", "formtastic" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>